[package]
name = "fastboot"
version = "0.1.0"
authors = ["rostyslav <rkhudolii@airtame.com>"]
publish = false
edition = "2021"

[lib]
name = "fastboot"

[dev-dependencies]
getopts = "*"
double = "*"
nusb = "=0.1.10"
usbio = { path = "./usbio" }
