[package]
name = "usbio"
version = "0.1.0"
authors = ["rostyslav <rkhudolii@airtame.com>"]
publish = false
edition = "2021"

[dependencies]
async-io = "2"
futures-lite = { version = "2", default-features = false }
nusb = "=0.1.10"
